trigger: none

pool:
 vmImage: ubuntu-latest

variables:
  - name: def_path
    value: '$(System.DefaultWorkingDirectory)/environment/dev'

  # - stage1 - init, validate and plan
  # - stage2 - code scanning
  # - stage3 - manual validation and apply

stages:
  - stage: initValidatePlan
    displayName: Init Validate and Apply
    jobs:
      - job: initPlan
        displayName: Init and Plan
        steps:

        - template: install-init.yaml

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(def_path)'
            environmentServiceNameAzureRM: 'fire'


      - job: validate
        dependsOn: initPlan
        displayName: Validate
        steps:
        - template: install-init.yaml
        - task: TerraformTask@5
          displayName: Terraform Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(def_path)'

  - stage: securityScan
    displayName: Security Scanning
    pool: fire
    jobs:
      - job: tfsecScan
        displayName: tfsec-scanning
        steps:
        - task: tfsec@1
          displayName: tfsec
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'

      - job: tflintScan
        steps:
        - task: CmdLine@2
          displayName: tflint scanning
          continueOnError: true
          inputs:
            script: 'tflint --chdir=$(System.DefaultWorkingDirectory) --recursive -f junit > tflint-result.xml'
            workingDirectory: '$(Build.ArtifactStagingDirectory)'
        - task: PublishTestResults@2
          displayName: tflint result publish
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'tflint-result.xml'
            searchFolder: '$(Build.ArtifactStagingDirectory)'
            failTaskOnFailedTests: true

  - stage: apply
    displayName: Apply
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: manualValidation
        displayName: Manual Approval
        pool: server
        steps:
        - task: ManualValidation@1
          displayName: Manual Approval
          inputs:
            notifyUsers: 'achinta.dutta04@gmail.com'
            approvers: 'achinta.dutta04@gmail.com'

      - job: apply
        dependsOn: manualValidation
        displayName: Apply
        steps:
        - template: install-init.yaml

        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(def_path)'
            environmentServiceNameAzureRM: 'fire'

  - stage: destroy
    condition: failed()
    displayName: Terraform Destroy
    jobs:
      - job: destroy
        steps:
        - template: install-init.yaml
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            workingDirectory: '$(def_path)'
            environmentServiceNameAzureRM: 'fire'
        